const CHECKLIST_QUESTION_TYPE = Object.freeze({
  BOOLEAN: "BOOLEAN",
  SINGLE_SELECT: "SINGLE_SELECT",
  MULTI_SELECT: "MULTI_SELECT",
  TEXT: "TEXT",
  IMAGE: "IMAGE"
});

module.exports = CHECKLIST_QUESTION_TYPE;
